### ISSUE TITLE
Contents

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/gh1#1]
The goal of __gh1__ is to make you a more useful collaborator by using R and GitHub. You will learn how to do common tasks using mostly GitHub and a little R, but you need not git or a link between GitHub and R.

## Contact forestgeo

- [x] Open a GitHub account.
- [x] Approve the account from your email.
- [x] [Request unlimited free private repos](https://github.com/forestgeo/learn/issues/22).
- [x] On github.com, Search GitHub for forestgeo/gh1.
- [x] Find this issue.
- [ ] Comment this issue:
    - Begin your comment with: Hi @maurolepore. This will send me an email, even if I am not watching __gh1__ (but not if I am ignoring it).
    - Then write your name and give me thumbs up (type ":" and thumbs will pop up)!

## Collaborate

- [x] Edit text in files of multiple formats:
    - .docx.
    - .Rmd.
    - .R.
- [x] File an issue in this repository following the [Issues Template](https://github.com/forestgeo/learn/issues/20). (There is one example in https://github.com/forestgeo/learn/issues/23.)

# Prepare for next tutorial

Install the software you will need (see [Initial Setup](http://r-pkgs.had.co.nz/git.html#git-init); if you need more help try http://happygitwithr.com/).

# Tutor only

- Show what you will be able to do in the next tutorial.

**Comment by teixeirak** [comment]
Another useful exercise would be for everyone to check basic data on their site:  https://github.com/forestgeo/Site-Data. If you are able to fill in any missing information or find any mistakes, edit and submit a pull request. Krista will approve and merge to the master version.

**Comment by matthewluskin** [comment]
Testing where this goes...

**Comment by jzambr** [comment]
Hi @maurolepore 

Jenny Zambrano

**Comment by MariaNatalia** [comment]
Hola @maurolepore soy Natalia

**Comment by srusso2** [comment]
@maurolepore hi it's sabrina russo doing your tutorial

**Comment by iverenabiem** [comment]
Hi @maurolepore . Ivy her 👍

**Comment by renatovalenciar** [comment]
@maurolepore Hi I am Renato

**Comment by awquebb** [comment]
Hi @maurolepore.

Andrew Quebbeman

**Comment by Chanpen** [comment]
@maurolepore 
Hi, I'm Chanpen--could you send me an email pls?

**Comment by sjosephwright** [comment]
@maurolepore  Joe Wright's user name is sjosephwright.

**Comment by laurenkrizel** [comment]
Hi @maurolepore - my username is laurenkrizel :":

**Comment by tzeleongyao** [comment]
@maurolepore 

Hi, am Yao. cheers

**Comment by shihongjia** [comment]
@maurolepore Hi, 
Shihong Jia.

**Comment by lcomita** [comment]
Hi @maurolepore  I am Liza.

**Comment by ZikunM** [comment]
@maurolepore 
Hello, my name is ZIkun.

**Comment by MusalmahN** [comment]
Hi @maurolepore . I'm Musalmah :+1:

**Comment by hmullerlandau** [comment]
@maurolepore    Hi,  Helene here.

**Comment by laosuz** [comment]
Hi Mauro, 
Please give me a password to access forestr.
Thanks,
Suzanne

**Comment by laurenkrizel** [comment]
Hi @maurolepore - my username is laurenkrizel

**Comment by pavel-fibich** [comment]
Hi @maurolepore Pavel

**Comment by Caicai112** [comment]
zhangcaicai@xtbg.org.cn

**Comment by kkkliuheming** [comment]
Hi @maurolepore my name is Heming

**Comment by dkenfack** [comment]
Hi, am David Ken

**Comment by mohizah** [comment]
Hi @maurolepore I'm Mohizah

**Comment by qmei4597** [comment]
Hi, @maurolepore am Mei

**Comment by maurolepore** [comment]
This issue was moved to forestgeo/tutorials#3

**Comment by maurolepore** [comment]
This issue was moved to https://github.com/forestgeo/tutorials/issues/3. __gh1__ will now live in https://github.com/forestgeo/tutorials.
